<?php

// STATUS OF GAME
define('STATUS_NEW_GAME', 0);
define('STATUS_WAITING_FOR_DIRECTION', 1);
define('STATUS_WAITING_FOR_ANSWER', 2);
define('STATUS_WAITING_FOR_NAME', 3);
define('STATUS_WAITING_FOR_EMAIL', 4);
define('STATUS_END_OF_GAME', 5);

// GAME CONSTS
define('PLAYER_STATUS', 'PLAYER_STATUS');



